[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
[target.wasm32-unknown-emscripten]
rustflags = [
    "-C", "link-args=-sSIDE_MODULE=2",
    "-C", "llvm-args=-enable-emscripten-cxx-exceptions=0",
    "-Z", "default-visibility=hidden",
    "-Z", "link-native-libraries=no",
    "-Z", "emscripten-wasm-eh=false",
]
[target.x86_64-pc-windows-msvc]
linker = "/mnt/extras/windevstuff/bin/x64/link.exe"
ar = "/mnt/extras/windevstuff/bin/x64/lib.exe"